# Generated by Django 5.1 on 2024-08-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflowers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inflow',
            old_name='quantily',
            new_name='quantity',
        ),
    ]
